### ISSUE TITLE
长时间未操作后，再次连接 无法连接。重试无效:NSmartProxy Server v1.0 ***

### ISSUE THREAD

**Issue by duyanming** [tmoonlight/NSmartProxy#29]
![image](https://user-images.githubusercontent.com/17999146/65414382-273ddd00-de26-11e9-803d-31bc3dacbaf2.png)
![image](https://user-images.githubusercontent.com/17999146/65414461-5a806c00-de26-11e9-8f97-c816bad76f41.png)

**Comment by duyanming** [comment]
怀疑是  心跳异常导致客户端重启 的时候 自动帮我切换了端口。

**Comment by tmoonlight** [comment]
配置发来看下，是用的http节点还是tcp的，http有这种bug，修复中

**Comment by TD-Hydro** [comment]
我也遇到的同样问题，我把windows 客户端的log贴在这里了，希望有所帮助
```
心跳循环被取消。
心跳循环已终止。
心跳异常导致客户端重启
未知异常。
连接故障，尝试关闭连接并重试
关闭反向链接：3，关闭节点连接：1
传输时出错：System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NSmartProxy.Client.Router.<OpenTrasferation>d__28.MoveNext()
连接关闭，开启重试
配置端口：反向连接端口7842,配置端口7841
ServerConnectionManager initialized.
Reading Config From Provider..
****************port list*************
1:  service.tdhydro.com:23948=>127.0.0.1:5901
**************************************
验证成功。
ClientID:693 AppId:1 已连接
Open server connection.
System.InvalidOperationException: The operation is not allowed on non-connected sockets.
   at System.Net.Sockets.TcpClient.GetStream()
   at NSmartProxy.NetworkUtil.<ConnectAndSend>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NSmartProxy.Client.ServerConnectionManager.<StartHeartBeats>d__23.MoveNext()
心跳循环被取消。
心跳循环已终止。
心跳异常导致客户端重启
未知异常。
连接故障，尝试关闭连接并重试
关闭反向链接：1，关闭节点连接：1
传输时出错：System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NSmartProxy.Client.Router.<OpenTrasferation>d__28.MoveNext()
连接关闭，开启重试
获取服务器端口失败：An error occurred while sending the request.
配置端口：反向连接端口7842,配置端口7841
ServerConnectionManager initialized.
Reading Config From Provider..
****************port list*************
1:  service.tdhydro.com:23948=>127.0.0.1:5901
**************************************
验证成功。
ClientID:693 AppId:1 已连接
Open server connection.
System.InvalidOperationException: The operation is not allowed on non-connected sockets.
   at System.Net.Sockets.TcpClient.GetStream()
   at NSmartProxy.NetworkUtil.<ConnectAndSend>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NSmartProxy.Client.ServerConnectionManager.<StartHeartBeats>d__23.MoveNext()
心跳循环被取消。
心跳循环已终止。
心跳异常导致客户端重启
未知异常。
连接故障，尝试关闭连接并重试
关闭反向链接：1，关闭节点连接：1
传输时出错：System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NSmartProxy.Client.Router.<OpenTrasferation>d__28.MoveNext()
连接关闭，开启重试
配置端口：反向连接端口7842,配置端口7841
ServerConnectionManager initialized.
Reading Config From Provider..
****************port list*************
1:  service.tdhydro.com:23948=>127.0.0.1:5901
**************************************
验证成功。
ClientID:693 AppId:1 已连接
Open server connection.
服务端心跳连接已关闭
心跳循环被取消。
心跳循环已终止。
心跳异常导致客户端重启
未知异常。
连接故障，尝试关闭连接并重试
关闭反向链接：1，关闭节点连接：1
传输时出错：System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NSmartProxy.Client.Router.<OpenTrasferation>d__28.MoveNext()
```
这是客户端的log，不能连接并且报错，在右下角的icon上显示绿色连接标志也不能连接
不过，手动再次打开客户端就又可以连接了

**Comment by tmoonlight** [comment]
> 我也遇到的同样问题，我把windows 客户端的log贴在这里了，希望有所帮助
> 
> ```
> 心跳循环被取消。
> 心跳循环已终止。
> 心跳异常导致客户端重启
> 未知异常。
> 连接故障，尝试关闭连接并重试
> 关闭反向链接：3，关闭节点连接：1
> 传输时出错：System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'System.Net.Sockets.NetworkStream'.
>    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
>    at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NSmartProxy.Client.Router.<OpenTrasferation>d__28.MoveNext()
> 连接关闭，开启重试
> 配置端口：反向连接端口7842,配置端口7841
> ServerConnectionManager initialized.
> Reading Config From Provider..
> ****************port list*************
> 1:  service.tdhydro.com:23948=>127.0.0.1:5901
> **************************************
> 验证成功。
> ClientID:693 AppId:1 已连接
> Open server connection.
> System.InvalidOperationException: The operation is not allowed on non-connected sockets.
>    at System.Net.Sockets.TcpClient.GetStream()
>    at NSmartProxy.NetworkUtil.<ConnectAndSend>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NSmartProxy.Client.ServerConnectionManager.<StartHeartBeats>d__23.MoveNext()
> 心跳循环被取消。
> 心跳循环已终止。
> 心跳异常导致客户端重启
> 未知异常。
> 连接故障，尝试关闭连接并重试
> 关闭反向链接：1，关闭节点连接：1
> 传输时出错：System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'System.Net.Sockets.NetworkStream'.
>    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
>    at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NSmartProxy.Client.Router.<OpenTrasferation>d__28.MoveNext()
> 连接关闭，开启重试
> 获取服务器端口失败：An error occurred while sending the request.
> 配置端口：反向连接端口7842,配置端口7841
> ServerConnectionManager initialized.
> Reading Config From Provider..
> ****************port list*************
> 1:  service.tdhydro.com:23948=>127.0.0.1:5901
> **************************************
> 验证成功。
> ClientID:693 AppId:1 已连接
> Open server connection.
> System.InvalidOperationException: The operation is not allowed on non-connected sockets.
>    at System.Net.Sockets.TcpClient.GetStream()
>    at NSmartProxy.NetworkUtil.<ConnectAndSend>d__8.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NSmartProxy.Client.ServerConnectionManager.<StartHeartBeats>d__23.MoveNext()
> 心跳循环被取消。
> 心跳循环已终止。
> 心跳异常导致客户端重启
> 未知异常。
> 连接故障，尝试关闭连接并重试
> 关闭反向链接：1，关闭节点连接：1
> 传输时出错：System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'System.Net.Sockets.NetworkStream'.
>    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
>    at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NSmartProxy.Client.Router.<OpenTrasferation>d__28.MoveNext()
> 连接关闭，开启重试
> 配置端口：反向连接端口7842,配置端口7841
> ServerConnectionManager initialized.
> Reading Config From Provider..
> ****************port list*************
> 1:  service.tdhydro.com:23948=>127.0.0.1:5901
> **************************************
> 验证成功。
> ClientID:693 AppId:1 已连接
> Open server connection.
> 服务端心跳连接已关闭
> 心跳循环被取消。
> 心跳循环已终止。
> 心跳异常导致客户端重启
> 未知异常。
> 连接故障，尝试关闭连接并重试
> 关闭反向链接：1，关闭节点连接：1
> 传输时出错：System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'System.Net.Sockets.NetworkStream'.
>    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
>    at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NSmartProxy.Client.Router.<OpenTrasferation>d__28.MoveNext()
> ```
> 
> 这是客户端的log，不能连接并且报错，在右下角的icon上显示绿色连接标志也不能连接
> 不过，手动再次打开客户端就又可以连接了

一楼的问题是bug，正在修复。。。你这边是否关闭了匿名登录？看看是不是和一楼同样的问题

**Comment by TD-Hydro** [comment]
服务器的错误log和一楼基本上是一样的所以我就没贴了

**Comment by tmoonlight** [comment]
新的1.1修复了端口变化导致重试无效的问题，另外如果是linux的服务器，长时间不操作会出现网络中断的现象，请在/etc/sysctl.conf文件中参照如下配置一下，防止socket连接中断：
        net.ipv4.tcp_keepalive_time = 300
        net.ipv4.tcp_keepalive_intvl = 10
        net.ipv4.tcp_keepalive_probes = 10
