### ISSUE TITLE
狂爆这个错误，什么情况

### ISSUE THREAD

**Issue by yuanxiongwei** [tmoonlight/NSmartProxy#38]
2020-02-20 22:43:47,169 [7] ERROR NSmartServer [(null)] - 登录信息异常。
System.Exception: 登录信息异常。
   at NSmartProxy.Infrastructure.Extension.HttpServer.ProcessHttpRequestAsync(HttpListenerContext context) in X:\3000git\NSmartProxy\src\NSmartProxy.Infrastructure\Extensions\HttpServer\HttpServer.cs:line 234
2020-02-20 22:43:47,345 [7] ERROR NSmartServer [(null)] - 登录信息异常。
System.Exception: 登录信息异常。
   at NSmartProxy.Infrastructure.Extension.HttpServer.ProcessHttpRequestAsync(HttpListenerContext context) in X:\3000git\NSmartProxy\src\NSmartProxy.Infrastructure\Extensions\HttpServer\HttpServer.cs:line 234
2020-02-20 22:43:47,347 [7] ERROR NSmartServer [(null)] - 登录信息异常。
System.Exception: 登录信息异常。
   at NSmartProxy.Infrastructure.Extension.HttpServer.ProcessHttpRequestAsync(HttpListenerContext context) in X:\3000git\NSmartProxy\src\NSmartProxy.Infrastructure\Extensions\HttpServer\HttpServer.cs:line 234
2020-02-20 22:43:52,028 [7] ERROR NSmartServer [(null)] - 登录信息异常。
System.Exception: 登录信息异常。
   at NSmartProxy.Infrastructure.Extension.HttpServer.ProcessHttpRequestAsync(HttpListenerContext context) in X:\3000git\NSmartProxy\src\NSmartProxy.Infrastructure\Extensions\HttpServer\HttpServer.cs:line 234
2020-02-20 22:43:52,036 [7] ERROR NSmartServer [(null)] - 登录信息异常。
System.Exception: 登录信息异常。
   at NSmartProxy.Infrastructure.Extension.HttpServer.ProcessHttpRequestAsync(HttpListenerContext context) in X:\3000git\NSmartProxy\src\NSmartProxy.Infrastructure\Extensions\HttpServer\HttpServer.cs:line 234
2020-02-20 22:43:52,039 [7] ERROR NSmartServer [(null)] - 登录信息异常。

**Comment by tmoonlight** [comment]
有人尝试不经登陆就访问你的nsmartproxy后台的api接口就会出这个错误，如果没有什么其他问题这里可以无视
