### ISSUE TITLE
最新版Linux服务端解压后运行报错

### ISSUE THREAD

**Issue by ysy950803** [tmoonlight/NSmartProxy#72]
就默认配置，直接报错，系统是CentOS 8.2，请问如何解决？
```
➜ 23:42:56 nspserver_scd_linux_v1.2_final4 ./NSmartProxy.ServerHost               
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Reflection.RuntimeAssembly.GetLocale()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   at System.Reflection.Assembly.GetName()
   at Microsoft.Extensions.PlatformAbstractions.ApplicationEnvironment..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..ctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices..cctor()
   at Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Default()
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(System.Action`1<PeterKottas.DotNetCore.WindowsService.HostConfigurator`1<System.__Canon>>)
   at NSmartProxy.ServerHost.Program.Main()
[1]    2252100 abort (core dumped)  ./NSmartProxy.ServerHost
```

**Comment by bazhengdao** [comment]
https://blog.csdn.net/weixin_42744102/article/details/107193189

**Comment by tmoonlight** [comment]
楼上正解
