### ISSUE TITLE
2017studio.imwork.net 拒绝了我们的连接请求。

### ISSUE THREAD

**Issue by 786744873** [tmoonlight/NSmartProxy#9]
2017studio.imwork.net 拒绝了我们的连接请求。
1:  2017studio.imwork.net:20064=>127.0.0.1:8093
**************************************
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): 由于连接方在一段时间后没有正确答复或连接的 主机没有反应，连接尝试失败。 113.116.156.12:9974
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at NSmartProxy.Client.ServerConnnectionManager.ConnectAppToServer(Int32 appid) in E:\3000开元\NSmartProxy\src\NSmartProxy.ClientRouter\ServerConnnectionManager.cs:line 128
   at NSmartProxy.Client.ServerConnnectionManager.PollingToProvider() in E:\3000开元\NSmartProxy\src\NSmartProxy.ClientRouter\ServerConnnectionManager.cs:line 107
   at NSmartProxy.Client.Router.ConnectToProvider() in E:\3000开元\NSmartProxy\src\NSmartProxy.ClientRouter\Router.cs:line 71
   at NSmartProxy.NSmartProxyClient.StartClient() in E:\3000开元\NSmartProxy\src\NSmartProxyClient\NSmartProxyClient.cs:line 75
One or more errors occurred. (由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 113.116.156.12:9974)

**Comment by tmoonlight** [comment]
telnet 9974端口 测试一下连通性

**Comment by 786744873** [comment]
不通的，是不是你那边的网络限制了亲

**Comment by tmoonlight** [comment]
你用的哪个版本？

**Comment by pjy612** [comment]
是不是 12308 端口 也被防火墙 墙了？

**Comment by tmoonlight** [comment]
> 是不是 12308 端口 也被防火墙 墙了？

服务暂时搭在我的树莓派上，有时不稳定，配置端口12308，连接端口19974
